 menuc8205c7636e728d448c2774e6a4a944b = {     {"Avahi SSH服务器浏览器", "/usr/bin/bssh", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Avahi VNC服务器浏览器", "/usr/bin/bvnc", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"Dropbox", "dropboxd", "/usr/share//icons/hicolor/16x16/apps/dropbox.png" },
     {"ELinks", "xterm -e /usr/bin/elinks ", "/usr/share//icons/gnome/16x16/mimetypes/html.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share//icons/hicolor/16x16/apps/firefox.png" },
     {"GmoteServer", "/opt/gmote/GmoteServer.sh", "///opt/gmote/gmote.png" },
     {"Google Chrome", "/opt/google/chrome/google-chrome ", "/usr/share//icons/hicolor/16x16/apps/google-chrome.png" },
     {"Opera", "/usr/bin/opera ", "/usr/share//icons/hicolor/16x16/apps/opera-browser.png" },
     {"Pidgin 互联网通讯程序", "pidgin", "/usr/share//icons/hicolor/16x16/apps/pidgin.png" },
     {"Psi", "psi ", "/usr/share//icons/hicolor/16x16/apps/psi.png" },
     {"Skype", "skype ", "/usr/share//icons/hicolor/16x16/apps/skype.png" },
     {"SpiderOak", "SpiderOak", "/usr/share/pixmaps/spideroak.png" },
     {"Transmission", "transmission-gtk ", "/usr/share//icons/hicolor/16x16/apps/transmission.png" },
     {"Wicd", "/usr/bin/wicd-client", "/usr/share//icons/hicolor/16x16/apps/wicd-gtk.png" },
     {"Wuala", "wuala", "/usr/share//icons/hicolor/64x64/apps/wuala.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"aLinkCreator", "alc", "/usr/share/pixmaps/alc.xpm" },
     {"aMule", "amule", "/usr/share/pixmaps/amule.xpm" },
     {"aMuleGUI", "amulegui", "/usr/share/pixmaps/amulegui.xpm" },
     {"wxCas", "wxcas", "/usr/share/pixmaps/wxcas.xpm" },
     {"傲兔 (Qt)", "hotot-qt", "/usr/share//icons/hicolor/22x22/apps/hotot.png" },
     {"阿里旺旺", "AliWangWang", "/usr/share/pixmaps/AliWangWang.png" },
 }

 menu5a0afc9dbd6c2e98769d4620d4fb5b13 = {     {"dosbox Emulator", "dosbox", "/usr/share/pixmaps/dosbox.png" },
 }

 menudb53804b7d726967c58fcc8c9ca03d27 = {     {"Adobe Reader 9", "acroread ", "/usr/share/pixmaps/acroread.png" },
     {"FBReader", "FBReader ", "/usr/share/pixmaps/FBReader.png" },
     {"LibreOffice ", "libreoffice ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"WPS 文字", "/usr/bin/wps", "/usr/share//icons/hicolor/48x48/apps/wps-office-wpsmain.png" },
     {"WPS 演示", "/usr/bin/wpp", "/usr/share//icons/hicolor/48x48/apps/wps-office-wppmain.png" },
     {"WPS 表格", "/usr/bin/et", "/usr/share//icons/hicolor/48x48/apps/wps-office-etmain.png" },
     {"Zathura", "zathura "},
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
 }

 menue1b7cee794666669f55acead93513971 = {     {"Blender", "blender", "/usr/share//icons/hicolor/16x16/apps/blender.png" },
     {"Dia 图表编辑器", "dia ", "/usr/share//icons/hicolor/16x16/apps/dia.png" },
     {"FontForge", "fontforge ", "/usr/share//icons/hicolor/16x16/apps/fontforge.png" },
     {"GNU 图像处理程序", "gimp-2.8 ", "/usr/share//icons/hicolor/16x16/apps/gimp.png" },
     {"Inkscape", "inkscape ", "/usr/share//icons/hicolor/16x16/apps/inkscape.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share//icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Pencil", "/usr/bin/pencil", "///usr/share/pencil/skin/classic/icon.svg" },
     {"图像查看器", "eog ", "/usr/share//icons/hicolor/16x16/apps/eog.png" },
 }

 menu526fe18cc54d217db3fdb0bf6c5e9bc8 = {     {"Audacity", "audacity ", "/usr/share//icons/hicolor/16x16/apps/audacity.png" },
     {"Avidemux (GTK+)", "avidemux2_gtk", "/usr/share/pixmaps/avidemux.png" },
     {"FlashPlayer", "flashplayer", "/usr/share/pixmaps/gflashplayer.png" },
     {"MuseScore", "mscore", "/usr/share/pixmaps/mscore.png" },
     {"PulseAudio Volume Control", "pavucontrol", "/usr/share//icons/gnome/16x16/apps/multimedia-volume-control.png" },
     {"QT V4L2 test Utility", "qv4l2", "/usr/share//icons/hicolor/16x16/apps/qv4l2.png" },
     {"VLC media player", "/usr/bin/vlc ", "/usr/share//icons/hicolor/16x16/apps/vlc.png" },
     {"gtk-recordMyDesktop", "gtk-recordMyDesktop", "/usr/share/pixmaps/gtk-recordmydesktop.png" },
 }

 menu8640cb1581c2ae2de5a1462405b2943b = {     {"DrRacket", "drracket", "/usr/share/pixmaps/drracket.xpm" },
     {"Stellarium nightsky renderer", "stellarium", "/usr/share/pixmaps/stellarium.png" },
 }

 menuba08216f13dd1742157412386eee1225 = {     {"Battle for Wesnoth", "wesnoth", "/usr/share/pixmaps/wesnoth-icon.png" },
     {"Battle for Wesnoth Map Editor", "wesnoth -e", "/usr/share/pixmaps/wesnoth_editor-icon.png" },
     {"Chromium B.S.U.", "chromium-bsu", "/usr/share/pixmaps/chromium-bsu.png" },
     {"Narcissu2-en", "/usr/bin/narcissu2-en", "/usr/share/pixmaps/narcissu2-en.png" },
     {"TeeWorlds", "teeworlds", "/usr/share/pixmaps/teeworlds.png" },
 }

 menu634d80d0a3e1eec96438b7071d9edc7f = {     {"Celestia", "celestia", "/usr/share/pixmaps/celestia.png" },
     {"SAGE", "xterm -e /opt/sage/sage -notebook", "///opt/sage/devel/ext-main/notebook/images/sageicon.png" },
 }

 menude71492af019157e5a5ef958b570e760 = {     {"Avahi Zero浏览器", "/usr/bin/avahi-discover", "/usr/share//icons/gnome/16x16/devices/network-wired.png" },
     {"ELF Library Viewer", "elflibviewer -caption \"ELF Library Viewer\" ", "/usr/share//icons/hicolor/48x48/apps/elflibviewer.png" },
     {"Fcitx", "fcitx", "/usr/share//icons/hicolor/16x16/apps/fcitx.png" },
     {"GParted", "gparted-pkexec", "/usr/share//icons/hicolor/16x16/apps/gparted.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"IBus", "ibus-daemon --xim"},
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share//icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"TrueCrypt", "truecrypt", "/usr/share/pixmaps/truecrypt.xpm" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wireshark", "wireshark ", "/usr/share//icons/hicolor/16x16/apps/wireshark.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce Terminal", "xfce4-terminal", "/usr/share//icons/gnome/16x16/apps/utilities-terminal.png" },
     {"dconf 系统配置编辑器", "dconf-editor", "/usr/share//icons/hicolor/32x32/apps/dconf-editor.png" },
     {"磁盘使用分析器", "baobab", "/usr/share//icons/hicolor/16x16/apps/baobab.png" },
     {"配置编辑器", "gconf-editor", "/usr/share//icons/hicolor/16x16/apps/gconf-editor.png" },
 }

 menu41282bf95e43c64d579757573a03cdde = {     {"Alleyoop", "alleyoop", "/usr/share//icons/hicolor/16x16/apps/alleyoop.png" },
     {"Android SDK", "android", "/usr/share/pixmaps/android-sdk.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"D-Feet", "d-feet", "/usr/share//icons/hicolor/16x16/apps/d-feet-icon.png" },
     {"DrRacket", "drracket", "/usr/share/pixmaps/drracket.xpm" },
     {"ELF Library Viewer", "elflibviewer -caption \"ELF Library Viewer\" ", "/usr/share//icons/hicolor/48x48/apps/elflibviewer.png" },
     {"Emacs", "emacs ", "/usr/share//icons/hicolor/16x16/apps/emacs.png" },
     {"Java Monitoring and Management Console", "jconsole", "/usr/share//icons/hicolor/16x16/apps/sun-java.png" },
     {"Java VisualVM", "jvisualvm", "/usr/share//icons/hicolor/16x16/apps/sun-java.png" },
     {"Meld", "meld ", "/usr/share//icons/hicolor/16x16/apps/meld.png" },
     {"Pencil", "/usr/bin/pencil", "///usr/share/pencil/skin/classic/icon.svg" },
     {"Qt Assistant", "/usr/bin/assistant", "/usr/share//icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "/usr/bin/designer", "/usr/share//icons/hicolor/128x128/apps/designer.png" },
     {"Qt Linguist", "/usr/bin/linguist", "/usr/share//icons/hicolor/16x16/apps/linguist.png" },
     {"SQLite Manager", "xulrunner /usr/share/sqlite-manager/application.ini -f ", "///usr/share/sqlite-manager/chrome/icons/default/default48.png" },
     {"bpython", "xterm -e /usr/bin/bpython"},
 }

 menuc9a6ee90f5d43732e3f6cf4dcaa8493c = {     {"7-Zip FM", "7zFM", "/usr/share//icons/hicolor/32x32/apps/p7zip.png" },
     {"FreeFileSync", "FreeFileSync", "///usr/share/FreeFileSync/Help/img/ffsicon.png" },
     {"Graphical Disk Map", "gdmap", "/usr/share/pixmaps/gdmap_icon.png" },
     {"Keyboard", "matchbox-keyboard", "/usr/share/pixmaps/matchbox-keyboard.png" },
     {"Leafpad", "leafpad ", "/usr/share//icons/hicolor/16x16/apps/leafpad.png" },
     {"Parcellite", "parcellite", "/usr/share/pixmaps/parcellite.png" },
     {"Qalculate!", "qalculate-gtk", "/usr/share/pixmaps/qalculate.png" },
     {"Root 终端", "gksu -l gnome-terminal", "/usr/share/pixmaps/gksu-root-terminal.png" },
     {"ScreenRuler", "screenruler", "/usr/share/pixmaps/screenruler-icon-32x32.png" },
     {"Screenkey", "screenkey", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-keyboard-shortcuts.png" },
     {"Shutter", "shutter ", "/usr/share//icons/hicolor/16x16/apps/shutter.png" },
     {"Skype Call Recorder", "skype-call-recorder", "/usr/share//icons/hicolor/128x128/apps/skype-call-recorder.png" },
     {"Sublime Text", "subl ", "/usr/share//icons/hicolor/16x16/apps/sublime_text.png" },
     {"bpython", "xterm -e /usr/bin/bpython"},
     {"gVim", "gvim ", "/usr/share/pixmaps/gvim.png" },
     {"字体查看器", "gnome-font-viewer ", "/usr/share//icons/gnome/16x16/apps/preferences-desktop-font.png" },
     {"字符映射表", "gucharmap", "/usr/share//icons/gnome/16x16/apps/accessories-character-map.png" },
     {"密码和密钥", "/usr/bin/seahorse", "/usr/share//icons/hicolor/16x16/apps/seahorse.png" },
     {"星际译王", "stardict", "/usr/share/pixmaps/stardict.png" },
     {"磁盘", "gnome-disks", "/usr/share//icons/hicolor/16x16/apps/gnome-disks.png" },
 }

xdgmenu = {    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"其它", menu5a0afc9dbd6c2e98769d4620d4fb5b13},
    {"办公", menudb53804b7d726967c58fcc8c9ca03d27},
    {"图像", menue1b7cee794666669f55acead93513971},
    {"影音", menu526fe18cc54d217db3fdb0bf6c5e9bc8},
    {"教育", menu8640cb1581c2ae2de5a1462405b2943b},
    {"游戏", menuba08216f13dd1742157412386eee1225},
    {"科学和数学", menu634d80d0a3e1eec96438b7071d9edc7f},
    {"系统工具", menude71492af019157e5a5ef958b570e760},
    {"编程", menu41282bf95e43c64d579757573a03cdde},
    {"附件", menuc9a6ee90f5d43732e3f6cf4dcaa8493c},
}

